spring:
  application:
    name: ecommerce
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/order
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  cache:
    type: simple
  messages:
    basename: messages
    encoding: UTF-8
#  mvc:
#    locale: tr
    #    locale: en_US
#    locale-resolver: fixed

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: order-group
      auto-offset-reset: earliest


server:
  port: 8080

#management:
#  endpoints:
#    web:
#      exposure:
#        include: refresh,health
